import NavBar from "@/components/NavBar";

type NavLink ={
    Name: string;
    href: string;
};

const links: NavLink[] = [
    {Name: "Услуги", href: "/doctor/services"},
    {Name: "Записи", href: "/doctor/appointments"}
]

export const metadata = {
    title: 'Next hospital',
    description: 'Generated by create next app',
  }
  

  export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
      <>
        <NavBar links={links}></NavBar> 
        <body>{children}</body>
      </>
    )
  }